### ISSUE TITLE
Example from README doesn't work

### ISSUE THREAD

**Issue by spakin** [tsudalab/fmqa#2]
I just tried **fmqa** for the first time, and got stuck trying to run the example from the README file:
```Python
#! /usr/bin/env python

import numpy as np
import fmqa

def two_complement(x, scaling=True):
    val, n = 0, len(x)
    for i in range(n):
        val += (1<<(n-i-1)) * x[i] * (1 if (i>0) else -1)
    return val * (2**(1-n) if scaling else 1)

xs = np.random.randint(2, size=(5,16))
ys = np.array([two_complement(x) for x in xs])

model = fmqa.FMBQM.from_data(xs, ys)
```

I'm receiving the following error message:
```
on_machine.py:109: SyntaxWarning: "is" with a literal. Did you mean "=="?
/tmp/fmqa-inst/lib/python3.8/site-packages/fmqa-0.0.1-py3.8.egg/fmqa/factorization_machine.py:109: SyntaxWarning: "is" with a literal. Did you mean "=="?
Traceback (most recent call last):
  File "/tmp/fmqa-test.py", line 15, in <module>
    model = fmqa.FMBQM.from_data(xs, ys)
  File "/tmp/fmqa-inst/lib/python3.8/site-packages/fmqa-0.0.1-py3.8.egg/fmqa/fm_binary_quadratic_model.py", line 72, in from_data
  File "/tmp/fmqa-inst/lib/python3.8/site-packages/fmqa-0.0.1-py3.8.egg/fmqa/fm_binary_quadratic_model.py", line 36, in __init__
  File "/tmp/fmqa-inst/lib/python3.8/site-packages/fmqa-0.0.1-py3.8.egg/fmqa/factorization_machine.py", line 82, in __init__
AttributeError: 'FactorizationMachine' object has no attribute 'name_scope'
```

This is with Python 3.8.3 on Ubuntu 20.10.

**Comment by yusekiya** [comment]
I had the same issue on Mac running macOS 11.4 on arm64 cpu arch. I settled the issue by installing mxnet=1.8.0 instead of the latest version.

**Comment by spakin** [comment]
That worked, @yusekiya!  I'm receiving a couple of `SyntaxWarning: "is" with a literal. Did you mean "=="?` warnings, but the code does actually run.

**Comment by UnixJunkie** [comment]
Almost same error here:
---
~/.local/lib/python3.8/site-packages/fmqa-0.0.1-py3.8.egg/fmqa/factorization_machine.py:109: SyntaxWarning: "is" with a literal. Did you mean "=="?
~/.local/lib/python3.8/site-packages/fmqa-0.0.1-py3.8.egg/fmqa/factorization_machine.py:109: SyntaxWarning: "is" with a literal. Did you mean "=="?
Traceback (most recent call last):
  File "./bin/fmqa_model.py", line 47, in <module>
    model = fmqa.FMBQM.from_data(xs, ys)
  File "~/.local/lib/python3.8/site-packages/fmqa-0.0.1-py3.8.egg/fmqa/fm_binary_quadratic_model.py", line 72, in from_data
  File "~/.local/lib/python3.8/site-packages/fmqa-0.0.1-py3.8.egg/fmqa/fm_binary_quadratic_model.py", line 36, in __init__
  File "~/.local/lib/python3.8/site-packages/fmqa-0.0.1-py3.8.egg/fmqa/factorization_machine.py", line 82, in __init__
AttributeError: 'FactorizationMachine' object has no attribute 'name_scope'
---

**Comment by UnixJunkie** [comment]
@yusekiya  maybe you can fix setup.py with the suggested version constraint?

**Comment by UnixJunkie** [comment]
Yes, those don't go away, even with mxnet==1.8.0
```
~/.local/lib/python3.8/site-packages/fmqa-0.0.1-py3.8.egg/fmqa/factorization_machine.py:109: SyntaxWarning: "is" with a literal. Did you mean "=="?
~/.local/lib/python3.8/site-packages/fmqa-0.0.1-py3.8.egg/fmqa/factorization_machine.py:109: SyntaxWarning: "is" with a literal. Did you mean "=="?
```
However, the fatal error goes away.

**Comment by UnixJunkie** [comment]
Several PRs could be accepted
https://github.com/tsudalab/fmqa/pull/5
https://github.com/tsudalab/fmqa/pull/3
then this issue could probably be closed

**Comment by k-kitai** [comment]
@UnixJunkie  Thank you for the bug fix.
I am closing this issue because the PRs #5 and #3 have been merged.
